import './globals.css'
import type { Metadata } from 'next'
import Context from './context/context'
export const metadata: Metadata = {
  title: 'Crypto Currency Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <Context>
        {children}
        </Context>
        </body>
    </html>
    
  )
}
